/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conwaygame;

import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.SwingUtilities;

import conwaygame.game.Controller;
import conwaygame.game.Game;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setResizable(false);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setTitle("Game of live");
        Game game = new Game(1500, 980, 60, 30);
        frame.add(game);
        frame.pack();
        frame.setVisible(true);
        game.start(new Controller(game));
    }
}
